#!/usr/bin/env bash
# Commit + push whatever progress is currently on disk.
#
# Same reasoning as the CGTrader sibling project: committing only once at the
# very end means any abrupt runner death loses the entire run's work. Calling
# this after every chunk bounds the loss to one chunk instead of hours.
#
# Usage: commit_progress.sh <label>
set -u

LABEL="${1:-progress}"

git config user.name "sketchfab-scraper-bot"
git config user.email "actions@users.noreply.github.com"

# The .cursor/.complete files MUST be committed too -- they are the resumable
# state that lets the next run continue instead of re-listing every category
# from page 1. Only the CSV exports are excluded (regenerated by --export,
# and could be large).
# One `git add a b c` call, not three separate ones: if ANY path in that list
# doesn't exist yet, git aborts the WHOLE command and stages NOTHING -- not
# even the paths that do exist and have real new content. This was the actual
# reason every single listing-only run (before the detail phase has ever run
# once, so sketchfab_details/ and sketchfab_comments/ don't exist yet) showed
# "nothing new to commit" while genuinely having thousands of freshly-listed
# models sitting on disk, confirmed by reproducing it in isolation: `git add
# real_dir nonexistent_dir` left real_dir untracked, `git status --short`
# still showed `?? real_dir/`, `git diff --staged --quiet` exited 0 (nothing
# staged). Adding each path only if it exists makes a missing one harmless.
for _p in sketchfab_raw sketchfab_details sketchfab_comments; do
  [ -e "$_p" ] && git add "$_p"
done

if git diff --staged --quiet; then
  echo "[commit] nothing new to commit for $LABEL"
  exit 0
fi

git commit -q -m "scrape progress ($LABEL): $(date -u +'%Y-%m-%d %H:%M UTC')"

# Sharded detail/comment files are append-mostly JSONL, deduped by uid on
# read, so when two commits touch the same shard file the correct
# resolution is the UNION of both sides, never "pick one" -- identical to
# the CGTrader project's fix for the same failure mode.
resolve_conflicts() {
  local f
  local any=0
  for f in $(git diff --name-only --diff-filter=U); do
    any=1
    echo "[commit]   union-merging conflicted $f"
    { git show ":2:$f" 2>/dev/null; git show ":3:$f" 2>/dev/null; } \
      | sort -u > "$f.union"
    mv "$f.union" "$f"
    git add "$f"
  done
  return $((1 - any))
}

for attempt in 1 2 3 4 5 6 7 8; do
  if git push -q; then
    echo "[commit] pushed $LABEL on attempt $attempt"
    exit 0
  fi
  echo "[commit] push rejected (attempt $attempt/8) -- fetching and rebasing"
  git fetch -q origin main
  if ! git rebase origin/main; then
    if resolve_conflicts; then
      GIT_EDITOR=true git rebase --continue >/dev/null 2>&1 || git rebase --abort
    else
      git rebase --abort
      echo "[commit] rebase failed with no conflicted files -- retrying"
    fi
  fi
  sleep $((attempt * 6 + RANDOM % 8))
done

echo "::error::push still failing after 8 attempts for $LABEL -- this chunk's progress is committed LOCALLY on the runner but could not reach origin/main."
exit 1
